language: cpp

compiler:
  - gcc
  - clang

sudo: false

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install lcov; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew unlink gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc6; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++ make debug ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then
      echo "Unsupported!" ; exit 1 ; fi
  - make test
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++ make release ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then
      echo "Unsupported!" ; exit 1 ; fi
  - make test
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make coverage ; fi

after_success:
    # Creating coverage report
  - ./coverage-report.sh
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - clang
      - libstdc++-7-dev
      - lcov
      - valgrind

cache: ccache

os:
  - linux
  - osx

# env:
#   - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

matrix:
  exclude:
    # clang on OSX not working ATM due to issues with brew downloading LLVM 5
    - os: osx
      compiler: clang

dist: trusty
