sudo: false

branches:
  except:
    - gh-pages

language: cpp

compiler:
  - gcc
  - clang


script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install lcov; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask uninstal oclint; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc6; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++ make debug ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then
      echo "Unsupported!" ; exit 1 ; fi
  - make test
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++ make release ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then
      echo "Unsupported!" ; exit 1 ; fi
  - make test
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make coverage ; make test ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      make doc ; fi


after_success:
    # Creating coverage report
  - lcov --directory build --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - clang
      - libstdc++-7-dev
      - lcov
      - valgrind
      - doxygen


cache: ccache

os:
  - linux
  - osx


# Environment
env:
  global:
    # - GH_REPO_REF: github.com/ondrik/libvata2.git
    # - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


matrix:
  exclude:
    # clang on OSX not working ATM due to issues with brew downloading LLVM 5
    - os: osx
      compiler: clang

# Ubuntu distribution
dist: trusty

# Deployment of GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: $TRAVIS_BUILD_DIR/doc/html
  keep-history: true
  on:
    branch: master
