language: cpp

compiler:
  - gcc
  - clang

sudo: false

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ;
    else
      make debug ;
    fi
  - make test
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ;
    else
      make release ;
    fi
  - make test

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      # - g++-4.8
      - g++-6
      - libstdc++-6-dev

cache: ccache

os:
  - linux
  - osx

# env:
#   - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

dist: trusty
