language: cpp

compiler:
  - gcc
  - clang

sudo: false

script:
  - make debug
  - make test
  - make release
  - make test

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      # - g++-4.8
      - g++-6
      - libstdc++-6-dev

cache: ccache

os:
  - linux
  - osx

env:
  - CC=gcc-6 && CXX=g++-6

dist: trusty
