language: cpp

compiler:
  - gcc
  - clang

sudo: false

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install lcov; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc6; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ;
    elif [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++ make debug ;
    elif [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make debug ;
    elif [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++-5.0 make debug ;
    else
      make debug ;
    fi
  - make test
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ;
    elif [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++ make release ;
    elif [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then
      CXX=g++-6 make release ;
    elif [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then
      CXX=clang++-5.0 make release ;
    else
      make release ;
    fi
  - make test

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      # - g++-4.8
      - g++-6
      - clang
      - libstdc++-7-dev
      - lcov
      - valgrind

cache: ccache

os:
  - linux
  - osx

# env:
#   - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

# matrix:
#   exclude:
#     # clang on OSX not working ATM due to issues with brew downloading LLVM 5
#     - os: osx
#       compiler: clang

dist: trusty
