name: Setup environment
description: Setup environment for running workflows.
inputs:
  os:
    description: 'Operating system to run on'
    required: false
    default: ubuntu-latest

runs:
  using: 'composite'
  steps:
    - name: Building MacOS dependencies
      if: ${{ github.event.inputs.os == 'macos-latest' }}
      shell: sh
      run: brew install lcov gcovr automake
    - name: Building Unix dependencies
      if: ${{ github.event.inputs.os == 'ubuntu-latest' }}
      shell: sh
      run: sudo apt-get install -y build-essential lcov gcovr xdg-utils
