name: Ubuntu (build-&-test)

on:
  push:
    branches: 
      - master 
      - devel
  pull_request:
    branches: 
      - master 
      - devel

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Unix dependencies 
        run: sudo apt-get install -y build-essential lcov gcovr xdg-utils
      - name: Compile the static and shared libraries
        run: make release
      - name: Test the library
        run: make test
