name: Check for Warnings

on: pull_request

jobs:
  setup-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Building Unix dependencies
        run: sudo apt-get install -y build-essential lcov gcovr xdg-utils

  setup-macos:
    runs-on: macos-latest
    steps:
      - name: Building MacOS dependencies
        run: brew install lcov gcovr automake

  compile-base:
    needs: [ setup-ubuntu, setup-macos ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Compile base version of the static and shared libraries
        run: make release 2>base_warnings
      - name: Cache file with warnings
        uses: actions/cache@v3
        env:
          cache-name: cache-warnings
        with:
          path: ./base_warnings
          key: warnings-base-${{ runner.os }}-${{ github.sha }}

  compile-new:
    needs: [ setup-ubuntu, setup-macos ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Compile new version of the static and shared libraries
        run: make release 2>new_warnings
      - name: Cache file with warnings
        uses: actions/cache@v3
        with:
          path: ./new_warnings
          key: warnings-new-${{ runner.os }}-${{ github.sha }}

  compare-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    needs: [ compile-base, compile-new ]
    steps:
      - name: Restore new cache
        uses: actions/cache/restore@v3
        with:
          path: ./new_warnings
          key: warnings-new-${{ runner.os }}-${{ github.sha }}
      - name: Restore base cache
        uses: actions/cache/restore@v3
        with:
          path: ./base_warnings
          key: warnings-base-${{ runner.os }}-${{ github.sha }}

      - name: Print base warnings
        run: cat base_warnings
      - name: Print new warnings
        run: cat new_warnings

      - name: Create comparison diff file
        run: |
          diff base_warnings new_warnings  | grep "^> *" | sed "s/^> //g" > comparison
          cat comparison

      - name: Count number of warnings
        run: |
          number_of_warnings=`cat comparison | grep "warning:" | wc -l`
          echo $number_of_warnings
          if [ $number_of_warnings -gt 0 ]; then
            exit 1
          fi
